import test from 'node:test';import assert from 'node:assert/strict';import '../data/location-indicators.js';
const source={status:'verified',sources:[{url:'https://example.org/evidence',checkedAt:'2026-09-16'}]};const assess=globalThis.LocationIndicators.assess;
test('missing and unproven indicators never become zero scores or an overall score',()=>{const r=assess({shinkansen:{minutes:0}});assert.equal(r.score,null);assert.equal(r.checked,0);assert.ok(r.rows.every(v=>v.points===null));});
test('Shinkansen boundaries include transfer wait and ceil fractional minutes',()=>{for(const [minutes,points] of [[0,3],[30,3],[30.1,2],[31,2],[60,2],[60.1,0]]){assert.equal(assess({shinkansen:{...source,minutes,station:'A',destination:'B',departureAt:'2026-09-16T09:00:00+09:00',includesTransferWait:true}}).rows[0].points,points);}assert.equal(assess({shinkansen:{...source,minutes:20,station:'A',destination:'B'}}).rows[0].points,null);});
test('partial restaurant discovery and wrong walking radius are not scored as complete surveys',()=>{const d={...source,count:25,walkingMeters:300,deduplicated:true,coverageComplete:true};assert.equal(assess({dining:d}).rows[1].points,5);assert.equal(assess({dining:{...d,coverageComplete:false}}).rows[1].points,null);assert.equal(assess({dining:{...d,walkingMeters:500}}).rows[1].points,null);});
test('one unknown brand is not treated as absent',()=>{assert.equal(assess({brands:{...source,starbucks:true}}).rows[2].points,null);assert.equal(assess({brands:{...source,starbucks:true,mcdonalds:true}}).rows[2].points,2);});
test('incomparable population and duplicate or out-of-range employers do not inflate score',()=>{assert.equal(assess({population:{...source,current:100000,previous:90000,comparable:false,periodYears:5,currentDate:'2026-08-01',previousDate:'2021-08-01'}}).rows[3].points,null);const site={siteId:'one',name:'factory',kind:'factory',minutes:30,majorEmployer:true};assert.equal(assess({employment:{...source,mode:'driving',coverageComplete:true,sites:[site,site,{...site,siteId:'far',minutes:31}]}}).rows[4].points,1);});
test('total is shown only when all five dimensions are evidenced',()=>{const r=assess({shinkansen:{...source,minutes:30,station:'A',destination:'B',departureAt:'2026-09-16T09:00:00+09:00',includesTransferWait:true},dining:{...source,count:25,walkingMeters:300,deduplicated:true,coverageComplete:true},brands:{...source,starbucks:true,mcdonalds:true},population:{...source,current:102000,previous:100000,comparable:true,periodYears:5,currentDate:'2026-08-01',previousDate:'2021-08-01'},employment:{...source,mode:'driving',coverageComplete:true,sites:[1,2,3,4].map(n=>({siteId:String(n),name:'Employer '+n,kind:'factory',minutes:30,majorEmployer:true}))}});assert.equal(r.checked,5);assert.equal(r.score,100);assert.equal(r.subtotal,18);});

test('population cannot label a two-year or invalid-date change as five years',()=>{for(const previousDate of ['2024-08-01','invalid','2021-02-30'])assert.equal(assess({population:{...source,current:102000,previous:100000,comparable:true,periodYears:5,currentDate:'2026-08-01',previousDate}}).rows[3].points,null);});
